### PR TITLE
Add Google Cloud Storage support.

### PR DESCRIPTION
**Pull request by bobobo1618**
For https://github.com/syncany/syncany/issues/427

A condition of being able to make this pull request was that the full text of the GPLv3 be included in a LICENSE file to make the legal state of the contribution clear.

### CODE REVIEW

**Comment by pimotte** [comment]
Looks good to me.

One little question/suggestion: Are there other implementations of S3-esque API's out there? It might be cleaner to have something like "S3Type.Google and "S3Type.AWS". That would make future extension a lot easier and I guess it probably reads cleaner too (instead of having isGoogle() { } else )

**Comment by bobobo1618** [comment]
There are but S3 itself and Google are the only variations supported by Jets3t which is the plugin currently in use and most S3-like APIs work without changes.

Really I'd like to move this to a more generic library like [jclouds](https://jclouds.apache.org/) or [dasein-cloud](https://github.com/greese/dasein-cloud) but that's a lot more work.

**Comment by binwiederhier** [comment]
We had a 'rest' plugin once that shipped with two classes 's3' and 'gs', but I eventually removed it because it made too much of a mess to have two plugins in one. Due to this experience, I'd suggest to just copy the S3 plugin and make a completely new plugin. 

Copying code is normally not a good thing, obviously, but it makes everything else soo much easier. Think of GUI/CLI implications and build stuff.

**Comment by bobobo1618** [comment]
I see why that might be a problem but I don't think maintaining two branches of this plugin is a good idea. If you had separate client libraries I'd understand but in reality, this is more of a Jets3t plugin than it is an S3 plugin since all it's really doing is providing a thin wrapper around it. 

I also think that given that the other plugins are for protocols rather than particular services, it makes more sense to stick to that convention with this plugin and keep both S3 implementations under the one S3 protocol plugin.

And keep in mind that this isn't just copying code once, this is copying code every time you need to make a change to the S3 plugin. I can pretty much guarantee you that maintaining split codebases will be more hellish than maintaining one with a few ternary operators and an extra config option.

**Comment by pimotte** [comment]
I recall that we used to have that plugin, but why did we remove the GS part? Apperently there is a demand for it, and I think we have all the InteractionListeners and such to make stuff work, right?

**Comment by cr0** [comment]
> And keep in mind that this isn't just copying code once, this is copying code every time you need to make a change to the S3 plugin. I can pretty much guarantee you that maintaining split codebases will be more hellish than maintaining one with a few ternary operators and an extra config option.

I share that opinion. However, I would prefer using enums over that `isGoogle` method even though there are no more providers available in jets3t. It simply looks cleaner.
Perhaps we can find a better way than having a separate boolean setting which is true if a user likes to use google. I'd quickly implement syncany/syncany#280 so we can provide a list with valid locations with one of them being google's.

**Comment by binwiederhier** [comment]
@bobobo1618 
I hear you and I agree that maintaining both plugins doesn't sound like fun either, so I tend to agree with you that it might have to go in one plugin. I would love to do proper inheritance like we did back then (see [1]), but I think that might just mess things up terribly, because all the build processes expect just one plugin and not two. 

With regards to the code: 
@bobobo1618 @cr0 Do we support boolean variables in the CLI/GUI wizard. Afaik there is no "checkbox" or dropbown being displayed in the GUI. How does the CLI behave if you enter "falzzee" instead of "true"/"false". 

If that behavior is clear and acceptable, we can merge the code.

[1] Old code:
http://bazaar.launchpad.net/~binwiederhier/syncany/trunk/files/head:/syncany/src/org/syncany/connection/plugins/rest/
http://bazaar.launchpad.net/~binwiederhier/syncany/trunk/files/head:/syncany/src/org/syncany/connection/plugins/gs/
http://bazaar.launchpad.net/~binwiederhier/syncany/trunk/files/head:/syncany/src/org/syncany/connection/plugins/s3/

**Comment by binwiederhier** [comment]
@cr0 ad "boolean": but we don't have a checkbox in the GUI for that, right? Do we have any plugin with a boolean field? I don't think so. I probably would've implemented a checkbox in the GUI by now if we had.

**Comment by cr0** [comment]
I don't think that we have any plugin which uses boolean values.

Enum PR waiting: syncany/syncany#430

**Comment by cr0** [comment]
@bobobo1618, the enum list feature is merged now. We'd be happy if you'd try the suggested approach. Perhaps you can also hardcode the available locations as enums and replace the free location text field in the settings.

**Comment by cr0** [comment]
@bobobo1618 I had a few minutes to make the `location` field use our new enum feature:
https://github.com/syncany/syncany-plugin-s3/tree/feature/enum-location/src/main/java/org/syncany/plugins/s3 feel free to use that as a basis.

**Comment by cr0** [comment]
Should we take over?

**Comment by binwiederhier** [comment]
@cr0 Hm?

**Comment by bobobo1618** [comment]
I haven't had much time recently to switch over to the enum unfortunately. Hopefully I'll have some time soon.

**Comment by binwiederhier** [comment]
Hey champ @bobobo1618, had time yet? :+1: 
If not just let us know and we'll take over.

**Comment by bobobo1618** [comment]
Haven't I'm afraid. If anyone can, go ahead :)

**Comment by cr0** [comment]
Superseded by #5

**Pull request closed without merging**
