### PR TITLE
Use ReadAfterWriteConsistent feature

### PR DESCRIPTION
**Pull request by cr0**
fixes syncany/syncany#448

### CODE REVIEW

**Comment by binwiederhier** [comment]
Perfect. Merge if you want :tada:

**Comment by binwiederhier** [comment]
dont forget to add it to the changelog.

**Comment by jgn** [comment]
Will this get into release soon? (I added https://github.com/syncany/syncany/issues/448)

**Comment by binwiederhier** [comment]
@jgn We just had a release, so it'll take a while for this to hit the next release, but you can always try/use the latest snapshots: `sy plugin remove s3; sy plugin install s3 --snapshot`

**Comment by binwiederhier** [comment]
(Wait a few minutes for it to be built though.)

**Comment by jgn** [comment]
Thanks!

**Comment by cr0** [comment]
@jgn: But be sure to use the latest Syncany release 0.4.5. I'm also happy if you can provide feedback if you experience any errors related to this change.

**Pull request merged**
